version: "3"

services:
  redis:
    container_name: test_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/test_redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always